---
- hosts: "{{ target_group }}"
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  serial: 1  # Process one host at a time
  tasks:
    - name: Ensure the host is reachable
      ping:

    - name: Reboot the LXC container
      command: shutdown -r now
      async: 1
      poll: 0
      register: reboot_command

    - name: Wait for the container to come back online
      wait_for_connection:
        timeout: 600  # Wait up to 10 minutes for the connection
      register: connection_status
      until: connection_status is success
      retries: 20  # Retry up to 20 times
      delay: 30    # Wait 30 seconds between retries

    - name: Debug connection status
      debug:
        var: connection_status