---
- hosts: "{{ target_group }}"
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  serial: 1  # Process one host at a time
  tasks:
    - name: Ensure the host is reachable
      ping:

    - name: Reboot the LXC container
      command: shutdown -r now
      async: 1
      poll: 0
      register: reboot_command

    - name: Wait for the container to come back online
      wait_for_connection:
        timeout: 600  # Increase timeout to 10 minutes
        delay: 30     # Wait 30 seconds before retrying
        retries: 10   # Retry up to 10 times