services:
  grafana:
    image: grafana/grafana-enterprise
    labels:
      - wud.trigger.include=dockercompose.grafana,gotify.local
      - wud.watch.digest=true
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
    - ./data:/var/lib/grafana
# volumes:
#   grafana-storage: {}