services:
  pia-wg-config:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pia-wg-config
    environment:
      - REGION=${REGION}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    entrypoint: ["sh", "-c", "pia-wg-config -r $REGION -v $USERNAME $PASSWORD"]
    # restart: unless-stopped